### ISSUE TITLE
Previous day of deactivated dates cannot be selected

### ISSUE THREAD

**Issue by UNCVR** [savvisingh/DateRangePicker#28] opened 2018-05-09 17:33 UTC
![dreamltexxr16nwalepage05092018193243](https://user-images.githubusercontent.com/18703480/39829781-c4577d96-53bf-11e8-9405-820ca6eea8c1.png)

As you can see on the screenshot above, the previous day of deactivated dates cannot be selected.

Here is the view initialisation code : 
```
calendarView
                .init(new Date(), addYear(new Date(), 1), new SimpleDateFormat("MMMM, YYYY", Locale.getDefault()))
                .inMode(CalendarPickerView.SelectionMode.RANGE)
                .withSelectedDate(new Date())
                .withDeactivateDates(new ArrayList<>(Collections.singletonList(7)));
```

**Comment by savvisingh** [comment] 2018-05-27 18:02
Hey man, sry the late reply, I tried reproducing the bug but it's working for me, if you can provide any stack trace, I can try and check what went wrong

**Comment by UNCVR** [comment] 2018-05-27 18:06
Hey,
It was linked to the timezone I'm in.

**Comment by savvisingh** [comment] 2018-05-28 18:16
I am not sure what you said, was it the bug related to the timezone?
Is it working fine now?

**Comment by softwrengr** [comment] 2018-12-25 08:46
hey,
The already selected date are not selecting can you help me ?

**Comment by savvisingh** [comment] 2019-05-22 08:28
Hi Since I am unable to reproduce this issue, and you are the only one reported this, I am closing this thread.
Feel free to open this if you face it again on the latest version of the lib

**Closed by savvisingh** 2019-05-22 08:28 UTC
